# Copyright (c) The Amphitheatre Authors. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

description = "A Cloud Native Buildpacks (CNB) builder with Paketo stacks (Jammy Jellyfish) and Leo buildpacks"

# [[buildpacks]]
#   id = "amp-buildpacks/leo"
#   uri = "docker://ghcr.io/amp-buildpacks/leo:0.1.5"

[[buildpacks]]
  id = "amp-buildpacks/leo-dist"
  uri = "docker://ghcr.io/amp-buildpacks/leo-dist:0.1.4"

[[buildpacks]]
  id = "amp-buildpacks/aleo"
  uri = "docker://ghcr.io/amp-buildpacks/aleo:0.1.5"

[[buildpacks]]
  id = "paketo-buildpacks/procfile"
  uri = "docker://gcr.io/paketo-buildpacks/procfile:5.6.8"


[lifecycle]
  version = "0.18.3"

[[order]]
  # [[order.group]]
  #   id = "amp-buildpacks/leo"
  #   version = "0.1.5"

  [[order.group]]
    id = "amp-buildpacks/leo-dist"
    version = "0.1.4"

  [[order.group]]
    id = "amp-buildpacks/aleo"
    version = "0.1.5"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.6.8"

[stack]
  id = "io.buildpacks.stacks.jammy"
  build-image = "docker.io/paketobuildpacks/build-jammy-base"
  run-image = "index.docker.io/paketobuildpacks/run-jammy-base"
